'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8922
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FSEARCH_BROWSER.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _144_1440352_credit_history_location_icon_png_blue_clipart_PUT_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("144_1440352_credit_history_location_icon_png_blue_clipart_PUT_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1jojvvcomkx9wyrexe4hgff7ypxzmq3jklp2kgpp2vspfe4i1z8xbzwtqhqa_2EE_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1jojvvcomkx9wyrexe4hgff7ypxzmq3jklp2kgpp2vspfe4i1z8xbzwtqhqa_2EE_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _698899_icon_18_bookmark_512_kE0_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("698899_icon_18_bookmark_512_kE0_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _username_login_1172579_jCB_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_username_login_1172579_jCB_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_512_v50_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_512_v50_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downloads_icon_rAH_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downloads_icon_rAH_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_mny_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_mny_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property library_773689_iKe_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("library_773689_iKe_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tools_wFk_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools_wFk_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
